/** Textos fixos do portal — fonte única para evitar corrupção de encoding nos TSX. */
export const PORTAL_COPY = {
  leaveYesterday: "DEIXE O ONTEM PARA TRÁS.",
  rebirthToday: "RENASÇA HOJE.",
  rebirthTodayAria: "Lema RENASÇA HOJE",
  brandName: "MECCAFIT CENTER",
  portalBrasaAria: "Portal de Brasa — dashboard principal",
  loadError: "Não foi possível carregar o altar.",
  profileUnavailable: "Perfil indisponível.",
  loginIdle: "Aproxime-se do altar para reacender sua jornada.",
  loginAltarAccess: "Cliente, administrador ou Dono Supremo acessam pelo altar principal.",
  loginPasswordHint:
    "Informe a senha de teste. Use senha123 para os usuários criados no Supabase.",
  loginOpening: "Abrindo o Portal de Brasa...",
  loginSessionError: "Não foi possível confirmar a sessão. Tente novamente.",
  loginProfileMissing:
    "Login reconhecido, mas o perfil não foi encontrado no altar. Contate o Forjador.",
  loginConfirmed: "Acesso confirmado no altar. Entrando no dashboard...",
  loginInvalidCredentials: "E-mail ou senha incorretos. Verifique suas credenciais e tente novamente.",
  loginRoleUnauthorized:
    "Este altar não reconhece o seu papel de acesso. Utilize o portal correto da sua linhagem.",
  loginDbError: "Falha ao validar o login no banco de dados. Tente novamente.",
  loginSubtitle: "Pronto para queimar os velhos hábitos?",
  onboardingTitle: "Primeiro Acesso Fenyxia",
  onboardingSubtitle: "Chave QR incandescente detectada. Forje sua identidade no altar.",
  onboardingInviteBanner:
    "Esta chave de ignição é de uso único. Complete seu cadastro para acender sua linhagem.",
  onboardingEmailRequired: "Informe o e-mail de acesso.",
  onboardingEmailInvalid: "Informe um e-mail válido.",
  onboardingPasswordMin: "A senha deve ter no mínimo 6 caracteres.",
  onboardingFullNameRequired: "Informe seu nome completo.",
  onboardingBirthInvalid: "Informe uma data de nascimento válida.",
  onboardingProcessing: "Forjando sua chave no altar...",
  onboardingSuccess: "Linhagem acesa. Entrando no dashboard...",
  onboardingSignupFailed: "Não foi possível concluir o primeiro acesso. Tente novamente.",
  onboardingConfirmEmail: "Conta criada. Confirme seu e-mail antes de acessar o altar.",
  onboardingInviteInvalid: "Convite inválido, expirado ou já utilizado.",
  onboardingInviteUnavailable: "Validação de convite indisponível. Tente novamente em instantes.",
  onboardingAlreadyHaveAccount: "Já possuo conta — ir para login",
  submitOnboarding: "ACENDER MINHA LINHAGEM",
  forgeSubtitle: "A Forja responde apenas à chave correta.",
  forgeActivateTitle: "Ative a sua",
  forgeActivateHighlight: "Forja.",
  forgeKeyPrompt: "Insira a Chave de Ignição da Forja",
  forgeKeyPlaceholder: "Chave de ignição da Forja",
  forgeValidating: "Validando chave no servidor...",
  forgeActivated: "Forja ativada. Informe os dados da sua Linhagem.",
  forgeNotConfigured: "Chave da Forja não configurada no servidor.",
  forgeKeyInvalid: "Digite a Chave de Ignição correta para liberar o cadastro.",
  forgeRegisterIncomplete: "Preencha Nome, E-mail Corporativo e Nome da Linhagem.",
  forgeRegisterLoading: "Iniciando ingestão segura no Supabase...",
  forgeRegisterSuccess:
    "Ingestão iniciada. Verifique o e-mail corporativo para concluir a ativação.",
  forgeRegisterError: "Falha inesperada ao iniciar o cadastro da Forja.",
  forgeBackToAltar: "← Voltar para o Altar",
  forgeCta: "Sou um Forjador (Ativar Minha Forja)",
  submitProcessing: "PROCESSANDO...",
  submitRegister: "Iniciar Inscrição",
  submitLogin: "REACENDER MINHA CHAMA",
  submitValidateForge: "VALIDAR CHAVE DA FORJA",
} as const;
