-- Meccafit — schema base (rodar ANTES das migrations ARGOS em projeto novo)
-- SQL Editor → New query → Run

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE public.user_role AS ENUM (
      'forjador',
      'forjador_linhagem',
      'forjador_soberano',
      'cliente'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'estagio_forca') THEN
    CREATE TYPE public.estagio_forca AS ENUM (
      'cinzas',
      'faisca',
      'brasa',
      'labareda',
      'fogo_cosmico_sagrado'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'subgrupo_muscular') THEN
    CREATE TYPE public.subgrupo_muscular AS ENUM (
      'costas',
      'peito',
      'ombros',
      'bracos',
      'pernas'
    );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now(),
  full_name text,
  nome_linhagem text,
  data_nascimento date NOT NULL DEFAULT '1990-01-01',
  role public.user_role NOT NULL DEFAULT 'cliente',
  forjador_id uuid REFERENCES public.profiles (id) ON DELETE SET NULL,
  status_altar text NOT NULL DEFAULT 'Ativo'
);

CREATE TABLE IF NOT EXISTS public.matriz_forca (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  cliente_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  musculo public.subgrupo_muscular NOT NULL,
  estagio public.estagio_forca NOT NULL DEFAULT 'cinzas',
  max_peso numeric(8, 2) NOT NULL DEFAULT 0,
  vtc_atual numeric(12, 2) NOT NULL DEFAULT 0,
  vtc_total numeric(12, 2) NOT NULL DEFAULT 0,
  total_sessoes integer NOT NULL DEFAULT 0,
  ultima_evolucao_em timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT matriz_forca_cliente_musculo_key UNIQUE (cliente_id, musculo),
  CONSTRAINT matriz_forca_max_peso_check CHECK (max_peso >= 0),
  CONSTRAINT matriz_forca_vtc_total_check CHECK (vtc_total >= 0),
  CONSTRAINT matriz_forca_total_sessoes_check CHECK (total_sessoes >= 0)
);

CREATE TABLE IF NOT EXISTS public.fenix_pureza_diaria (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  cliente_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  data date NOT NULL,
  pureza_percentual numeric(5, 2) NOT NULL DEFAULT 0,
  agua_litros numeric(5, 2),
  sono_horas numeric(4, 2),
  treino_realizado boolean NOT NULL DEFAULT false,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fenix_pureza_diaria_cliente_data_key UNIQUE (cliente_id, data),
  CONSTRAINT fenix_pureza_diaria_pureza_check CHECK (
    pureza_percentual >= 0 AND pureza_percentual <= 100
  )
);

CREATE TABLE IF NOT EXISTS public.historico_treinos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users (id) ON DELETE CASCADE,
  cliente_id uuid REFERENCES public.profiles (id) ON DELETE CASCADE,
  exercicio_id integer NOT NULL DEFAULT 0,
  exercicio_nome text NOT NULL DEFAULT 'Treino geral',
  musculo text NOT NULL DEFAULT 'peito',
  peso numeric(8, 2),
  peso_atual numeric(8, 2) NOT NULL DEFAULT 0,
  repeticoes integer NOT NULL DEFAULT 1,
  series integer NOT NULL DEFAULT 1,
  status text,
  registrado_em timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.historico_treino (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  cliente_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  matriz_forca_id uuid REFERENCES public.matriz_forca (id) ON DELETE SET NULL,
  musculo public.subgrupo_muscular NOT NULL,
  exercicio_id text NOT NULL DEFAULT 'geral',
  exercicio_nome text NOT NULL DEFAULT 'Treino geral',
  peso numeric(8, 2) NOT NULL DEFAULT 1,
  repeticoes integer NOT NULL DEFAULT 1,
  series integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'CONCLUÍDO',
  registrado_em timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.planos_semanais (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  forjador_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  semana_inicio date NOT NULL,
  treinos_prescritos integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS profiles_forjador_id_idx ON public.profiles (forjador_id);
CREATE INDEX IF NOT EXISTS matriz_forca_cliente_id_idx ON public.matriz_forca (cliente_id);
CREATE INDEX IF NOT EXISTS fenix_pureza_diaria_cliente_id_data_idx
  ON public.fenix_pureza_diaria (cliente_id, data DESC);
CREATE INDEX IF NOT EXISTS historico_treinos_cliente_id_idx
  ON public.historico_treinos (cliente_id);
CREATE INDEX IF NOT EXISTS historico_treino_cliente_id_registrado_em_idx
  ON public.historico_treino (cliente_id, registrado_em DESC);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_profiles_updated_at ON public.profiles;
CREATE TRIGGER set_profiles_updated_at
BEFORE UPDATE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_matriz_forca_updated_at ON public.matriz_forca;
CREATE TRIGGER set_matriz_forca_updated_at
BEFORE UPDATE ON public.matriz_forca
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_fenix_pureza_diaria_updated_at ON public.fenix_pureza_diaria;
CREATE TRIGGER set_fenix_pureza_diaria_updated_at
BEFORE UPDATE ON public.fenix_pureza_diaria
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.on_auth_user_created()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_role public.user_role;
  v_musculo public.subgrupo_muscular;
BEGIN
  IF nullif(NEW.raw_user_meta_data ->> 'data_nascimento', '') IS NULL THEN
    RAISE EXCEPTION 'data_nascimento é obrigatório no cadastro do perfil.'
      USING ERRCODE = '23502';
  END IF;

  v_role := CASE
    WHEN NEW.raw_user_meta_data ->> 'role' = 'forjador_soberano' THEN 'forjador_soberano'::public.user_role
    WHEN NEW.raw_user_meta_data ->> 'role' = 'forjador' THEN 'forjador'::public.user_role
    ELSE 'cliente'::public.user_role
  END;

  INSERT INTO public.profiles (
    id,
    full_name,
    nome_linhagem,
    data_nascimento,
    role,
    status_altar
  )
  VALUES (
    NEW.id,
    coalesce(
      nullif(NEW.raw_user_meta_data ->> 'full_name', ''),
      nullif(NEW.raw_user_meta_data ->> 'name', '')
    ),
    nullif(NEW.raw_user_meta_data ->> 'nome_linhagem', ''),
    (NEW.raw_user_meta_data ->> 'data_nascimento')::date,
    v_role,
    coalesce(nullif(NEW.raw_user_meta_data ->> 'status_altar', ''), 'Ativo')
  )
  ON CONFLICT (id) DO UPDATE SET
    full_name = coalesce(EXCLUDED.full_name, public.profiles.full_name),
    data_nascimento = EXCLUDED.data_nascimento,
    role = EXCLUDED.role,
    updated_at = now();

  FOREACH v_musculo IN ARRAY enum_range(NULL::public.subgrupo_muscular)
  LOOP
    INSERT INTO public.matriz_forca (cliente_id, musculo)
    VALUES (NEW.id, v_musculo)
    ON CONFLICT (cliente_id, musculo) DO NOTHING;
  END LOOP;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.on_auth_user_created();

CREATE OR REPLACE FUNCTION public.calcular_estagio_forca(p_vtc_total numeric)
RETURNS public.estagio_forca
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    WHEN p_vtc_total >= 100000 THEN 'fogo_cosmico_sagrado'::public.estagio_forca
    WHEN p_vtc_total >= 50000 THEN 'labareda'::public.estagio_forca
    WHEN p_vtc_total >= 20000 THEN 'brasa'::public.estagio_forca
    WHEN p_vtc_total >= 5000 THEN 'faisca'::public.estagio_forca
    ELSE 'cinzas'::public.estagio_forca
  END;
$$;

-- Stubs exigidos pelas migrations ARGOS (substituídos depois)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.atualizar_estagio_muscular()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.registrar_treino_com_status(
  p_user_id uuid,
  p_exercicio_id text,
  p_peso_atual numeric,
  p_data date,
  p_exercicio_nome text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RAISE EXCEPTION 'registrar_treino_com_status ainda não migrado — rode migrations ARGOS'
    USING ERRCODE = 'P0001';
END;
$$;

CREATE OR REPLACE FUNCTION public.registrar_treino_com_status(
  p_exercicio_id integer,
  p_exercicio_nome text,
  p_musculo text,
  p_peso_atual numeric,
  p_repeticoes integer,
  p_series integer,
  p_user_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RAISE EXCEPTION 'registrar_treino_com_status ainda não migrado — rode migrations ARGOS'
    USING ERRCODE = 'P0001';
END;
$$;

CREATE OR REPLACE VIEW public.vw_renascimento_fenix
WITH (security_invoker = true)
AS
SELECT
  p.id AS cliente_id,
  p.full_name,
  p.role,
  p.forjador_id,
  p.status_altar,
  mf.musculo,
  mf.estagio,
  mf.max_peso,
  mf.vtc_total,
  mf.total_sessoes,
  mf.ultima_evolucao_em,
  fpd.data AS pureza_data,
  fpd.pureza_percentual,
  fpd.treino_realizado
FROM public.profiles p
LEFT JOIN public.matriz_forca mf ON mf.cliente_id = p.id
LEFT JOIN public.fenix_pureza_diaria fpd ON fpd.cliente_id = p.id;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matriz_forca ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fenix_pureza_diaria ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.historico_treinos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.historico_treino ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.planos_semanais ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA public TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated, service_role;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO authenticated, service_role;
